### ISSUE TITLE
UserControl

### ISSUE THREAD

**Issue by wingadium1** [TCS-PROJECT/CustomerManager#1]
User Login Logout, Search User, Change Password

**Comment by wingadium1** [comment]
Update code at branch https://github.com/TCS-PROJECT/CustomerManager/tree/issues/UserControl
Assign for Tung

**Comment by wingadium1** [comment]
assign for @tungnkse02153

**Comment by tungnkse02153** [comment]
đã up Login Logout Change Password Seach User

**Comment by wingadium1** [comment]
sau khi login đã thêm username and password vào session

**Comment by wingadium1** [comment]
done
