### ISSUE TITLE
Customer Control

### ISSUE THREAD

**Issue by wingadium1** [TCS-PROJECT/CustomerManager#3]
Customer control nhiệm vụ chính liên quan đến các bài toán quản lý customer thêm sửa xóa.
Assign cho @bachcanhki 

Customer control được update ở nhánh 
https://github.com/TCS-PROJECT/CustomerManager/tree/issues/CustomerControl

**Comment by bachcanhki** [comment]
Đã xong 2 chức năng add và search Customer
Chưa có valid date

**Comment by bachcanhki** [comment]
```
        function validateform() {
            var name = document.myform.txtNa.value;
            var add = document.myform.txtDes.value;
            var income = document.myform.txtPrice.value;
```

/check giá trị của tên khách hàng
                if (name == null || name == "") {
                    alert("Customer name can't be blank");
                    return false;
                }
/check giá trị của địa chỉ khách hàng
                if (add == null || add == "") {
                    alert("Address can't be blank");
                    return false;
                }

 / cần tạo một function check ngày tháng đúng định dạng dd/mm/yyyy
               var dob = document.myform.txtMnf.value;
               isDate(dob);
               var st = document.myform.txtStart.value;
               isDate(st);
               var en = document.myform.txtEnd.value;
               isDate(en);

/ check giá trị date xem ngày bắt đầu có nhỏ hơn ngày kết thúc không
                var start = Date.parse(document.myform.txtStart.value.split('/').reverse().join('/'));
                var end = Date.parse(document.myform.txtEnd.value.split('/').reverse().join('/'));
                if (start > end) {
                    alert("Start date in must before End date");
                    return false;
                }

/ check giá trị date xem ngày nhập vào có phải ngày trong quá khứ hay không
/ giá trị nhập vào phải là ngày trước ngày hiện tại
                var q = new Date();
                var m = q.getMonth() + 1;
                var d = q.getDay();
                var y = q.getFullYear();

```
            var today = new Date(y, m, d);

            var mdate = new Date(document.myform.txtMnf.value.split('/').reverse().join('/'));

            if (mdate > today)
            {
                alert("Date of birth can't be in future!");
                return false;
            }
```

/ check giá trị của thu nhập cá nhân khách hàng
/ giá trị nhập vào phải là số thực vào lớn hơn 0
                if (income == null || income == "") {
                    alert("Income can't be blank");
                    return false;
                } else {
                    var ic = parseFloat(income);
                    if (isNaN(ic)) {
                        alert("Income must be positive number");
                        return false;
                    }
                    else if (ic <= 0) {
                        alert("Income must be greater than 0");
                        return false;
                    }
                }

```
        }
```

**Comment by bachcanhki** [comment]
Cập nhật thêm validate
-kiểm tra dữ liệu nhập vào
-kiểm tra dữ liệu trống

**Comment by bachcanhki** [comment]
Thêm chức năng Update và Delete
Cập nhật file myscript.js

**Comment by wingadium1** [comment]
add about page, close issues

**Comment by wingadium1** [comment]
merged to master
